In [179]:
# simple,multiple,polynomial linear regression
# input col and output col
# simple linear regression --> LOS, Gradient decent

## Creating Our simple Linear regression Model

In [180]:

class Lr:
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,x_train,y_train):
        num = 0
        den = 0
        
        for i in range(x_train.shape[0]):
            num += ((x_train[i] - x_train.mean()) * (y_train[i] - y_train.mean()))
            den += (x_train[i] - x_train.mean())**2
            
        self.m = (num / den)
        self.b = (y_train.mean() - (self.m * x_train.mean()))
        
        print(self.m)
        print(self.b)
        
    
    def predict(self,x_test):
        
        return (self.m * x_test) + self.b
    
    

### Downloading the dataset ('placement.csv')

In [202]:
# !wget https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day48-simple-linear-regression/placement.csv

In [182]:
import pandas as pd
import numpy as np

In [183]:
data = pd.read_csv('placement.csv')
data.head(10)

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57
5  7.89     2.99
6  6.73     2.60
7  6.75     2.48
8  6.09     2.31
9  8.31     3.51

In [184]:
# want to exctract in numpy columns thats why we will use "df.iloc[:].values"
x = data.iloc[:,0].values
y = data.iloc[:,1].values

# x = data['cgpa']
# y = data['package']
# x.head(),y.head()

In [185]:
x.shape

(200,)

In [186]:
y.shape

(200,)

**importing the train_test_split from sklearn.model_selection**

In [187]:
from sklearn.model_selection import train_test_split


In [188]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [189]:
x_train.shape[0]

160

### **creating the object model**

In [190]:
model = Lr()

In [191]:
#To train the dataset
model.fit(x_train,y_train)

0.5579519734250721
-0.8961119222429152


In [200]:
#To predict, also cheaking the predicting value VS actual value
model.predict(x_test[0]),y_test[0]

(array([3.89111601]), array([4.1]))

## Now Training With help of Sklearn.Linear_model

In [193]:
from sklearn.linear_model import LinearRegression

In [194]:
lr = LinearRegression()

In [195]:
x = data.iloc[:,0].values.reshape(-1,1)
y = data.iloc[:,1].values.reshape(-1,1)


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)
type(x_test)

numpy.ndarray

In [196]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [197]:
lr.coef_,lr.intercept_

(array([[0.55795197]]), array([-0.89611192]))

In [201]:
lr.predict(x_test[0].reshape(1,1)),y_test[0]

(array([[3.89111601]]), array([4.1]))

**Accuracy**

In [199]:
lr.score(x_test,y_test)

0.780730147510384